/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : anthony
 * Created : 11/13/2015 08:17:22
 */

package org.anthonytest.newtest;

import org.compression.helpers.CompressAndCountFiles;
import org.junit.*;
import static org.junit.Assert.*;

import java.lang.String;



public class CompressFilesTest {

	/**
	 *
	 * @see org.compression.helpers.CompressAndCountFiles#decompressGzipFile(String,String)
	 */
	@org.junit.Test
	public void decompressGzipFile() {
		CompressAndCountFiles.decompressGzipFile("","");
	}

	
}
